### ISSUE TITLE
v1.1.2 failure

### ISSUE THREAD

**Issue by warped-rudi** [notspiff/visualization.shadertoy#20]
At least the GLES implemention on Freescale iMX6 (Vivante) doesn't like the reordering introduced in dc091296f7db8744b675a010218097a8dff5ce7a I.e. it wants the "#extension ..." statement to come first.

**Comment by warped-rudi** [comment]
A quick check shows that it fails on RaspberryPi as well.

**Comment by notspiff** [comment]
thanks. i did the same as it did in the old code before the merger, but
apparently that was a broken guide then. will fix.

**Comment by notspiff** [comment]
should be taken care of.
