### ISSUE TITLE
Define preset in settings

### ISSUE THREAD

**Issue by hawkeyexp** [notspiff/visualization.shadertoy#21]
Hi, nice visualization. Can you possible add the option to predefine a single preset in the settings which will be always used ?

Thx

**Comment by notspiff** [comment]
no need. hit 'l' or whatever is mapped to 'LockPreset' on your input device. presets are managed by the application, not the visualisation.

**Comment by hawkeyexp** [comment]
Oh sorry not noticed - thx for feedback !
