### ISSUE TITLE
how to compile with openglesv2 on osmc? Default compiled with opengl.

### ISSUE THREAD

**Issue by virserg** [notspiff/visualization.shadertoy#42]
how to compile with openglesv2 on osmc? Default compiled with opengl.
Help, please.

**Comment by Rechi** [comment]
configure with APP_RENDER_SYSTEM=gles

**Comment by wsnipex** [comment]
this should be autodetected if /usr/share/kodi/cmake/KodiConfig.cmake has been installed correctly
