### ISSUE TITLE
Would the new leia version work on 18.5?

### ISSUE THREAD

**Issue by kraaa** [notspiff/visualization.shadertoy#54]
I'm happy to try if somebody supply an build for x64 windows.
I have spent 3 hours trying to build and it's beyond me.

**Comment by AlwinEsch** [comment]
You can try this:
```
git clone --branch Leia https://github.com/xbmc/xbmc.git kodi
git clone --branch Leia https://github.com/xbmc/visualization.shadertoy.git
cd visualization.shadertoy && mkdir build && cd build
cmake -G "Visual Studio 15 Win64" -T host=x64 -DADDONS_TO_BUILD=visualization.shadertoy -DADDON_SRC_PREFIX=../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:/Users/<YOUR_USER_PATH>/AppData/Roaming/Kodi/addons -DPACKAGE_ZIP=1  ../../kodi/cmake/addons
cmake --build . --config "Release"
```

Change the `<YOUR_USER_PATH>` to yours and should be then installed to Kodi's system path.

But the binary should already available for Kodi to load and is here http://mirrors.kodi.tv/addons/leia/visualization.shadertoy+windows-x86_64/

**Comment by kraaa** [comment]
Oh it's 1.2.3 I thought it was a newer one that was the same as the Matrix version i tried. Thought they were the same.

**Comment by AlwinEsch** [comment]
On Matrix it is more different as it can use a normal OpenGLES with the Angle (https://github.com/google/angle), but that's not available and possible on Leia :unamused:.

On Leia it should also work as it simulate GL on DirectX with a bit reworked shaders.

If you try them from Matrix, there you become a lot of failures on Leia :smile:

**Comment by kraaa** [comment]
Oh i see. Yes it works on Leia it's just the one shader/preset i really like does not :(
Thanks for your time and helping dumb me understand 👍
