### ISSUE TITLE
The build for Nexus ends with error

### ISSUE THREAD

**Issue by mkreisl** [notspiff/visualization.shadertoy#79]
Now the time has come. The chaos in building the binary addons once again occurred again

It still says **visualization.shadertoy https://github.com/xbmc/visualization.shadertoy Matrix**
in the **Nexus** branch of **repo-binary-addons** inside

And since you have so little influence in these witty buildscripts, please correct ASAP!

Thanks

**Comment by lrusak** [comment]
Why not make the PR yourself?

Time is limited right now and people are slowly working on updating the add-ons for Nexus (which isn't at all ready so I'm not sure why you are trying to use it).

**Comment by mkreisl** [comment]
What kind of helpfully stupid behavior is that?
Instead of being happy that one draws attention to abuses, comes as an answer why I already use Nexus
Really great, thank you very much. Now you know why I don't do PR's here

**Comment by lrusak** [comment]
> What kind of helpfully stupid behavior is that?

Thanks for bring up the fact that it's not working as it should, we know this and as I said we are slowly working on it.

**Comment by mkreisl** [comment]
Slowly, yes indeed. I did my first Nexus build already in the beginning of May. That's 4 months if I calculate correctly.
I really don't see any problem in creating the appropriate branches and adapting the branch as soon as the new name for the new Kodi is found. This can be done in one go and really only takes minutes. This is what I mean by chaos, the binary addon building is in my eyes simply PITA, far too time consuming and error prone.
I have been doing this for a few years now, I think I know exactly what I am talking about.

But nevertheless I want to thank @AlwinEsch  for being the only one who really cares about binary addons as far as I can see.

**Comment by AlwinEsch** [comment]
Yes, sorry that not comes faster. The last months I was a bit away by private things. Will look to make the changes on all addons, but that really much.

As there was no API change, can a addon from Matrix also works on Nexus. The only type where becomes soon a change, is the PVR type, where then Matrix no more works on Nexus by this type.

**Comment by AlwinEsch** [comment]
Has you mean by build error a missing <json/json.h> include?

Created a fix here https://github.com/xbmc/visualization.shadertoy/pull/82 and on version 19.1.1 & 20.1.1 in.

**Comment by mkreisl** [comment]
Yes, exactly. I had this error

And yes, I already noticed that you had created a fix for it. I'm now waiting for the repo-binary-addons to be adjusted accordingly

But probably the Matrix branch will work again after the fix.

Thanks a lot
